server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}
    external_labels:
      job: fastapi-auth

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) - \[?(?P<level>\w+)\]? - (?P<logger>\w+) - (?P<file>[\w\.]+)\.(?P<function>\w+)\((?P<line>\d+)\) - (?P<message>.*)'
      - labels:
          level:
          logger:
          file:
          function:
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/log/**/*.log
